import { ACTION_TYPES_PREFIX } from 'store/common';

export const SET_INCREASING_INFO = `${ACTION_TYPES_PREFIX}SET_INCREASING_INFO`;
export const RESET_INCREASING_INFO = `${ACTION_TYPES_PREFIX}RESET_INCREASING_INFO`;
