import { ACTION_TYPES_PREFIX } from 'store/common';

export const SET_INACCESSIBLE_DESTINATION = `${ACTION_TYPES_PREFIX}SET_INACCESSIBLE_DESTINATION`;
export const RESET_INACCESSIBLE_DESTINATION = `${ACTION_TYPES_PREFIX}RESET_INACCESSIBLE_DESTINATION`;
