import { ACTION_TYPES_PREFIX } from 'store/common';

export const GENERATE_NEXT_CIRCLES = `${ACTION_TYPES_PREFIX}GENERATE_NEXT_CIRCLES`;
export const NEXT_CIRCLES_GENERATED = `${ACTION_TYPES_PREFIX}NEXT_CIRCLES_GENERATED`;
