import { ACTION_TYPES_PREFIX } from './constants';

export const INIT_LINES = `${ACTION_TYPES_PREFIX}INIT_LINES`;
export const INIT_NEXT_POSITION = `${ACTION_TYPES_PREFIX}INIT_NEXT_POSITION`;
export const RESET_REDUX_STATE = `${ACTION_TYPES_PREFIX}RESET_REDUX_STATE`;
